"""SQLAlchemy ORM models for the Nexa database.

This module defines the schema for the SQLite database, including the
Conversation and Message models which represent chat history.
"""
from sqlalchemy import Column, Integer, String, Text, DateTime
from sqlalchemy.ext.declarative import declarative_base
from datetime import datetime

# Base class for declarative models
Base = declarative_base()

class Conversation(Base):
    """Conversation metadata for a chat session.
    
    Represents a single chat thread within the application,
    storing the title and creation timestamp.
    """
    __tablename__ = "conversations"
    
    # Unique identifier for the conversation
    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    # Human-readable title, usually generated by the LLM
    title = Column(String, default="New Chat")
    # Timestamp when the conversation was initiated
    created_at = Column(DateTime, default=datetime.now)

class Message(Base):
    """A single message entry tied to a conversation.
    
    Contains the role (user or assistant), text content,
    and optional image payload encoded in base64.
    """
    __tablename__ = "messages"
    
    # Unique identifier for the message
    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    # Foreign key referencing the parent conversation
    conversation_id = Column(Integer)
    # The role of the message sender (e.g., 'user', 'assistant')
    role = Column(String)
    # The text content of the message
    content = Column(Text)
    # Optional base64 encoded string representing an attached image
    image_base64 = Column(Text, nullable=True)
    # Timestamp when the message was sent
    created_at = Column(DateTime, default=datetime.now)